Class {
	#name : #SanoPlasmaModel,
	#superclass : #Object,
	#category : 'AKG-SanoPlasma-Model'
}

{ #category : #testing }
SanoPlasmaModel >> isChain [
	"Answer a boolean indicating if the receiver is a SanoPlasma Chain"

	^false
]

{ #category : #testing }
SanoPlasmaModel >> isFrequencyRange [
	"Answer a boolean indicating if the receiver is a SanoPlasma Frequency Range"

	^false
]

{ #category : #testing }
SanoPlasmaModel >> isPreset [
	"Answer a boolean indicating if the receiver is a SanoPlasma Preset"

	^false
]

{ #category : #testing }
SanoPlasmaModel >> isProgram [
	"Answer a boolean indicating if the receiver is a SanoPlasma Program"

	^false
]

{ #category : #testing }
SanoPlasmaModel >> isSettings [
	"Answer a boolean indicating if the receiver is a SanoPlasma Settings"

	^false
]
