Class {
	#name : #Spooky2SignalGeneratorSimulator,
	#superclass : #Spooky2SignalGenerator,
	#category : 'AKG-Spooky2-Model'
}

{ #category : #'initialize-release' }
Spooky2SignalGeneratorSimulator >> close [ 
]

{ #category : #actions }
Spooky2SignalGeneratorSimulator >> connect [
	"Connect to the signal generator"

]

{ #category : #accessing }
Spooky2SignalGeneratorSimulator >> writeCommand: aString [
]
